/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ejercicio6;

/**
 *
 * @author Usuario
 */
public class JPanelSistema extends javax.swing.JPanel {

    /**
     * Creates new form JPanelInicio
     */
    public JPanelSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(600, 500));
        setLayout(new java.awt.GridLayout(2, 1));

        jPanel4.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setText("jLabel1");
        jPanel4.add(jLabel1);

        jLabel13.setText("Medac Aulas");
        jPanel4.add(jLabel13);

        jLabel14.setText("pc16ana");
        jPanel4.add(jLabel14);

        jLabel15.setText("Windows Update");
        jPanel4.add(jLabel15);

        add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(4, 1));

        jLabel19.setText("Sonido");
        jPanel5.add(jLabel19);

        jLabel17.setText("Pantalla");
        jPanel5.add(jLabel17);

        jLabel16.setText("Notificaciones");
        jPanel5.add(jLabel16);

        jLabel20.setText("Concentracion");
        jPanel5.add(jLabel20);

        add(jPanel5);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
