/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ejercicio6;

/**
 *
 * @author Usuario
 */
public class JPanelRed extends javax.swing.JPanel {

    /**
     * Creates new form JPanelRed
     */
    public JPanelRed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(600, 500));
        setLayout(new java.awt.GridLayout(7, 1, 10, 10));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        jLabel1.setText("wi-fi (Medac Aulas)");
        jPanel1.add(jLabel1);

        jLabel3.setText("Propiedades");
        jPanel1.add(jLabel3);

        jLabel2.setText("Uso de datos");
        jPanel1.add(jLabel2);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jLabel5.setText("Wifi");
        jPanel2.add(jLabel5);

        jLabel4.setText("Activado");
        jPanel2.add(jLabel4);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jLabel7.setText("Ethernet");
        jPanel3.add(jLabel7);

        jLabel6.setText("Autenticación, configuración DNS e IP, red de uso medio");
        jPanel3.add(jLabel6);

        add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(2, 1));

        jLabel8.setText("VPN");
        jPanel4.add(jLabel8);

        jLabel9.setText("Agregar, conectar, administrar");
        jPanel4.add(jLabel9);

        add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        jLabel11.setText("Zona con cobertura inalámbrica móvil");
        jPanel5.add(jLabel11);

        jLabel10.setText("Desactivado");
        jPanel5.add(jLabel10);

        add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jLabel13.setText("Modo Avión");
        jPanel6.add(jLabel13);

        jLabel12.setText("Desactivado");
        jPanel6.add(jLabel12);

        add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(2, 0));

        jLabel14.setText("Proxy");
        jPanel7.add(jLabel14);

        jLabel15.setText("Servidor proxy para conexiones WI-FI y Ethernet");
        jPanel7.add(jLabel15);

        add(jPanel7);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
