/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ejercicio6;

/**
 *
 * @author Usuario
 */
public class JPanelInicio extends javax.swing.JPanel {

    /**
     * Creates new form JPanelInicio
     */
    public JPanelInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(600, 500));
        setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/ejercicio6/Captura de pantalla 2024-10-08 135322.png"))); // NOI18N
        jPanel1.add(jLabel1);

        jLabel3.setText("Medac Aulas");
        jPanel1.add(jLabel3);

        jLabel2.setText("pc16ana");
        jPanel1.add(jLabel2);

        jLabel4.setText("Windows Update");
        jPanel1.add(jLabel4);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(4, 1));
        jPanel2.add(jLabel5);

        jLabel6.setText("Todo está aqui con la cuenta de Microsoft");
        jPanel2.add(jLabel6);

        jLabel7.setText("Inicia sesión oara conectar sus aplicaciones");
        jPanel2.add(jLabel7);

        jButton1.setText("Iniciar Sesión");
        jPanel2.add(jButton1);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(4, 2));

        jLabel8.setText("Configuración Recomendada");
        jPanel3.add(jLabel8);

        jLabel9.setText("Aplicaciones Instaladas");
        jPanel3.add(jLabel9);

        jLabel10.setText("Sonido");
        jPanel3.add(jLabel10);

        jLabel11.setText("Pantalla");
        jPanel3.add(jLabel11);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
