/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicio1;

/**
 *
 * @author Ana
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jProducto = new javax.swing.JLabel();
        jPrecio = new javax.swing.JLabel();
        jUnidades = new javax.swing.JLabel();
        j1 = new javax.swing.JLabel();
        jNom1 = new javax.swing.JTextField();
        jP1 = new javax.swing.JTextField();
        jU1 = new javax.swing.JTextField();
        j2 = new javax.swing.JLabel();
        jNom2 = new javax.swing.JTextField();
        jP2 = new javax.swing.JTextField();
        jU2 = new javax.swing.JTextField();
        j3 = new javax.swing.JLabel();
        jNom3 = new javax.swing.JTextField();
        jP3 = new javax.swing.JTextField();
        jU3 = new javax.swing.JTextField();
        j4 = new javax.swing.JLabel();
        jNom4 = new javax.swing.JTextField();
        jP4 = new javax.swing.JTextField();
        jU4 = new javax.swing.JTextField();
        j5 = new javax.swing.JLabel();
        jNom5 = new javax.swing.JTextField();
        jP5 = new javax.swing.JTextField();
        jU5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButtonCalcular = new javax.swing.JButton();
        jLPrecioTotal = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(7, 4, 10, 10));
        getContentPane().add(jLabel1);

        jProducto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jProducto.setText("Producto");
        getContentPane().add(jProducto);

        jPrecio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPrecio.setText("Precio");
        getContentPane().add(jPrecio);

        jUnidades.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jUnidades.setText("Unidades");
        getContentPane().add(jUnidades);

        j1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        j1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        j1.setText("1");
        getContentPane().add(j1);

        jNom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNom1ActionPerformed(evt);
            }
        });
        getContentPane().add(jNom1);
        getContentPane().add(jP1);
        getContentPane().add(jU1);

        j2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        j2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        j2.setText("2");
        getContentPane().add(j2);
        getContentPane().add(jNom2);
        getContentPane().add(jP2);
        getContentPane().add(jU2);

        j3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        j3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        j3.setText("3");
        getContentPane().add(j3);
        getContentPane().add(jNom3);
        getContentPane().add(jP3);
        getContentPane().add(jU3);

        j4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        j4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        j4.setText("4");
        getContentPane().add(j4);
        getContentPane().add(jNom4);
        getContentPane().add(jP4);
        getContentPane().add(jU4);

        j5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        j5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        j5.setText("5");
        getContentPane().add(j5);
        getContentPane().add(jNom5);
        getContentPane().add(jP5);
        getContentPane().add(jU5);
        getContentPane().add(jLabel10);

        jButtonCalcular.setBackground(new java.awt.Color(0, 153, 153));
        jButtonCalcular.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonCalcular.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcular);

        jLPrecioTotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLPrecioTotal.setText("Precio total:");
        getContentPane().add(jLPrecioTotal);

        jTextField7.setEditable(false);
        getContentPane().add(jTextField7);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNom1ActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        public void actionPerformed(ActionEvent e) {
                 double total = 0;
 
                 //For que comprueba que los textfields no esten vacios y coge los textos introducidos
                 for (int i = 0; i < 5; i++) {
                     // Comprobar que no estén vacíos
                     if (precioFields[i].getText().isEmpty() || unidadFields[i].getText().isEmpty() || productoFields[i].getText().isEmpty()) {
                         JOptionPane.showMessageDialog(frame, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
                         return;
                     }
 
                     nombreProductos[i] = productoFields[i].getText();
                     precios[i] = Double.parseDouble(precioFields[i].getText());
                     unidades[i] = Double.parseDouble(unidadFields[i].getText());
 
                     total += precios[i] * unidades[i];
                 }
 
                 lresultado.setText(String.format("%.2f", total)); // Mostrar resultado con dos decimales
 
                 // Construir una cadena para mostrar los resultados
                 StringBuilder resultado = new StringBuilder();
                 for (int i = 0; i < 5; i++) {
                    //recorrer el array e ir añadiendo los arrays
                     resultado.append(nombreProductos[i]).append(": ").append(String.format("%.2f", precios[i] * unidades[i])).append("€\n");
                 }
                 resultado.append("Precio Total: ").append(String.format("%.2f", total));
                 JOptionPane.showMessageDialog(frame, resultado.toString(), "Resultado", JOptionPane.INFORMATION_MESSAGE);
             }
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j5;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JLabel jLPrecioTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JTextField jNom1;
    private javax.swing.JTextField jNom2;
    private javax.swing.JTextField jNom3;
    private javax.swing.JTextField jNom4;
    private javax.swing.JTextField jNom5;
    private javax.swing.JTextField jP1;
    private javax.swing.JTextField jP2;
    private javax.swing.JTextField jP3;
    private javax.swing.JTextField jP4;
    private javax.swing.JTextField jP5;
    private javax.swing.JLabel jPrecio;
    private javax.swing.JLabel jProducto;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jU1;
    private javax.swing.JTextField jU2;
    private javax.swing.JTextField jU3;
    private javax.swing.JTextField jU4;
    private javax.swing.JTextField jU5;
    private javax.swing.JLabel jUnidades;
    // End of variables declaration//GEN-END:variables
}
